name = "eat-sheet"
main = "src/server/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "eat-sheet.com/*", zone_name = "eat-sheet.com" },
  { pattern = "www.eat-sheet.com/*", zone_name = "eat-sheet.com" },
]

[assets]
directory = "dist/client"
not_found_handling = "none"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "eat-sheet-db"
database_id = "a606f1f7-605f-4f8e-9c5d-9e3b1a789752"

[[r2_buckets]]
binding = "LOGOS"
bucket_name = "eat-sheet-logos"

[vars]
COMMIT_SHA = "unknown"
