name = "eat-sheet-api"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
main = "src/server/index.ts"

routes = [
  { pattern = "eat-sheet.com/api/*", zone_name = "eat-sheet.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "eat-sheet-db"
database_id = "a606f1f7-605f-4f8e-9c5d-9e3b1a789752"
migrations_dir = "src/server/db/migrations"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "eat-sheet-photos"
