export const CUISINES = [
  "American",
  "Asian Fusion",
  "Bakery/Cafe",
  "Barbecue",
  "Brazilian",
  "Chinese",
  "Deli",
  "Dessert",
  "French",
  "Greek",
  "Indian",
  "Italian",
  "Japanese",
  "Korean",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Pizza",
  "Seafood",
  "Southern",
  "Thai",
  "Vietnamese",
  "Other",
] as const;

export type Cuisine = (typeof CUISINES)[number];
