-- Auto-generated by seed-brian-restaurants.py
-- DO NOT EDIT MANUALLY

-- Create Brian as a member of The Butlers family
INSERT OR IGNORE INTO members (family_id, name, is_admin, email)
  SELECT id, 'Brian Dickinson', 0, 'bsdickinson@gmail.com'
  FROM families WHERE invite_code = 'Tiny2019';

-- Insert 239 restaurants

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Proper Fish', 'Fish &  chips', 'Bainbridge Island', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bistro San Martin', 'Upscale', 'Arlington', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Mean Sandwich', 'Sandwiches', 'Ballard', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Dosa House', 'Indian', 'Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'El Gaucho', 'Steakhouse', 'Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kira Sushi', 'Sushi', 'Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Tendon Kohaku', 'Tempura', 'Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Tang Bar', 'Hot pot', 'Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ashland Brewery', 'Craft Brewery', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Boundary Bay Brewing', 'Craft Brewery', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Home skillet', 'Diner', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Naan and Brew', 'Indian', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Dianna''s Italian', 'Italian', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jalapeno''s', 'Mexican', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Starla''s', 'Pizza', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pel'' meni', 'Russian Dumplings', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bushara''s Thai', 'Thai', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Black Sheep', 'Upscale Tacos', 'Bellingham', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Tavern on the Square @ Anderson School', 'American', 'Bothell', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ta Joia - Latin Korean fusion', 'Korean/Latin Fusion', 'Bothell', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Julio’s - Mexican', 'Mexican', 'Bothell', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kin Dee Thai', 'Thai', 'Bothell', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Railroad Pub & Pizza', 'Pub and Pizza', 'Burlington', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sakura (sushi)', 'Sushi', 'Burlington', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bateau', 'French/steak', 'Capital Hill', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Blotto', 'Pizza', 'Capital Hill', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Honey Hole', 'Sandwiches', 'Capitol Hill', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Macho Burger', 'Burger - Fish & Chips', 'Clearview', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Clearview Thai Stop', 'Thai', 'Clearview', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Wild Ginger', 'Asian Variety', 'Des Moines', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Wally''s Chowder House', 'Seafood', 'Des Moines', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Other Side Market & Cafe', 'BLT', 'Eastlake', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rusty Pelican', 'Breakfast', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Moto Pizza', 'Detroit pizza', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Niles Peacock Pizza', 'Pizza', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Church Key', 'Pub food', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Market', 'Seafood', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Salt and Iron', 'Steakhouse', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'SanKai', 'Sushi', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Scott''s Bar and Grill', 'Prime rib', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Buck''s American Cafe', 'American', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Totem Family diner', 'American B''fast/Lunch', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'King Noodle House', 'Asian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Fogo de Chão Brazilian Steakhouse', 'Brazilian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ray''s Drive In', 'Burgers', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Frying Lemon Fish', 'Chinese', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Piroshky & Crepes', 'European bakery', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sisters Restaraunt', 'Family', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Net Shed Fish Market', 'Fish', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Curries', 'Indian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Lombardi''s', 'Italian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Capers and Olives', 'Italian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Luca Italian Restaurant', 'Italian', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Wasabi garden', 'Japanese', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sodam Chicken', 'Korean Chicken', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sweet Radish', 'Korean chicken', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'El Pariso', 'Mexican', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Memo''s Mexican Food', 'Mexican', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Brooklyn Bros.', 'Pizza', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, '7th Street Pub', 'Pub Food', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Botan Ramen n Bar', 'Ramen', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Wood Fire Grill', 'Seafood & beef', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Emory''s on Silver Lake', 'Seafood and more', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Scuttlebutt', 'Seafood and other', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The New Mexicans', 'Southwest', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, '16Eleven', 'Steak', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Katana', 'Sushi', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kai', 'Sushi', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Nom nom Teriaki & More', 'Teriaki', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Washington Burrito', 'Mexican', 'Everett / Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Triangle Spirits', 'Fried Chicken', 'Fremont', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Local Tide', 'Shrimp Toast', 'Fremont', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Omega Pizza', 'Italian', 'Granite Falls', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Playa Bonita', 'Mexican', 'Granite Falls', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'North Star Diner', 'Diner', 'Greenwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Windy City Pie', 'Pizza', 'Greenwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Junebaby', 'Southern/fusion', 'Greenwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Index Grocery Store', 'Korean', 'Index', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Harbor City', 'Dim Sum', 'International District', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jade Garden', 'Dim Sum', 'International District', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Purple Dot', 'Dim Sum', 'International District', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Diamond Bay', 'Sushi', 'International District', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'E-Jae Pak Mor', 'Thai', 'International District', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Guest House', 'American/brunch', 'Kenmore', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Lucky House', 'Dim Sum', 'Kent', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Supreme Dumplings', 'Dumplings', 'Kirkland', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Paridido', 'Italian', 'Kirkland', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Cactus', 'Mexican', 'Kirkland', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bella Balducci''s - Persian Fod', 'Persian', 'Kirkland', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ray''s Boat House', 'Seafood', 'Kirkland', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Shambles', 'Prime meats', 'Lake City', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Teriyaki Diner', 'Asian', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Lucky Dragon', 'Chinese', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Conto''s', 'Italian', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Nacho’s', 'Mexican', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Razzle', 'Sports Bar', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Buzz Inn', 'Steaks', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kiyama sushi', 'Sushi', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'LJ Bistro', 'Upscale American', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Pines', 'Upscale Bar', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Hawkeye''s Pub', 'Bar Food', 'Lake Strevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ellis Island Casino', 'Variety and inexpensive', 'Las Vegas', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Indigo Kitchen and Alehouse', 'American', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jet''s Pizza', 'Detroit Pizza', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'T&T Seafood', 'Dim Sum', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Budapest Bistro', 'Hungarian', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Wild wasabi', 'Japanese', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Chops', 'Korean Burritos', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kabob Korner', 'Mediterranean', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, '•Bruciato•', 'Pizza', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Biddy Fish', 'Sushi', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Isarn soul kitchen', 'Thai', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'TK Noodle', 'Thai', 'Lynnwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Maltby Cafe', 'Breakfast', 'Maltby', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Russel''s', 'Steak', 'Maltby', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, '1933 Bar & Kitchen', 'American', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Beijing Chinese Cuisine', 'Chinese', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Noble Palace', 'Chinese', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Don’s 24 hour cafe', 'Diner', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Christiano''s', 'Italian', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Korea House', 'Korean BBQ', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'El Rey', 'Mexican', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pho', 'Pho', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Osaka', 'Sushi', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jeff''s BBQ', 'Texas BarBQue', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Village Taproom and Grill', 'American', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bleacher''s Grill at Cedar Crest GC', 'Burgers and more', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Fanny''s', 'Diner - b''fast', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Volli', 'Sports', 'Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'McMenamins', 'American', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rusty Pelican', 'American', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sawmill Cafe', 'American', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'China City', 'Chinese', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Clay Pit', 'Indian', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Azul Restaraunt and Louge', 'Latin American', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Tablas', 'Spanish - Tapas', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rare Society', 'Steak', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Momo Sushi', 'Sushi', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sushi Spott', 'Sushi', 'Mill Creek/Silver Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Lewis and Main', 'American', 'Monroe', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bella Balducci''s - Med Food', 'Mediterranean', 'Monroe', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pho Than Nah', 'Pho', 'Monroe', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kadhai Indian Cuisine', 'Indian', 'Monroe', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Hong Kong', 'Chinese', 'Mt Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Calico Cupboard', 'American', 'Mt. Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'I''ll Granaio', 'Italian', 'Mt. Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'COA', 'Mexican', 'Mt. Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rachawadee Thai Cafe', 'Thai', 'Mt. Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Diamond Knot Brewery', 'Pub', 'Mukilteo', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Big Mario''s', 'Pizza', 'Northlake', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Fortuna Bottega', 'Italian Sando''s', 'Phinney Ridge', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Skalka', 'Georgian Bakery', 'Pike Place', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rhodie''s Smokin'' BBQ', 'BBQ', 'Preston', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Zio Sal Ristorante', 'Italian', 'Redmond', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pancake Chef', 'Diner', 'SeaTac', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Din Ti Fung', 'Asian', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Woodshop BBQ', 'BBQ', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Portage Bay', 'Brunch', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Larson''s Bakery', 'Danish Bakery', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Matt''s Famous', 'Hot Dogs', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Agua Verde', 'Mexican', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Marakesh', 'Moroccan', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Saint Bread', 'Pastry', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Don Lucho''s', 'Peruvian', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bar Solea (downtown)', 'Pizza', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Yard house brewery', 'Pub', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Asean Streat Food Hall', 'SE Asian hawker stalls', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kashiba', 'Sushi', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Tai Tung', 'Chinese', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'LePichet', 'French', 'Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Rey Amago Chocolate Shop', 'Mexican Chocolate', 'Seattle - Cap Hill', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kau Kau', 'Chinese', 'Seattle International', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Diamond Bay', 'Dim Sum', 'Seattle International', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ciudad - bar and grill', 'Grilled Meats', 'Seattle International', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Fonda La Catrina', 'Mexican', 'Seattle International', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Paddy Coynes', 'Irish pub and grill', 'Seattle or Bellevue', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Purple Cafe and Wine Bar', 'American', 'Seattle or Woodinville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Double Barrel BBQ', 'BBQ', 'Sedro Wolly', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Cabbage Patch', 'American', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Collector''s Choice Restaraunt', 'American', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Repp', 'American', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'First and Union and Kitchen', 'American - bfast', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Snohomish Bakery', 'Baked Goods', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Oxford Saloon', 'Burger', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Hops and Drops', 'Burgers, etc.', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jake''s Cafe''', 'Diner', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'The Pie Dive Bar', 'Dinner and Dessert Pie', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Roger’s Riverside Bistro', 'Fine Dining', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'El Paraiso Mexican Grill', 'Mexican', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'South Lake Pizza', 'Pizza', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Westside Pizza', 'Pizza', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Andy’s Fish House', 'Seafood', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Trail''s End', 'American', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Double Barrel Wine Bar', 'American', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Heidi''s Sandwich Board', 'Deli', 'Snohomish', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kami Teriyaki', 'Teriyaki', 'Snohomish, Marysville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pick-Quick Drive In', 'Burgers&fries', 'SODO', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Coconut Kenny''s', 'Deli', 'South Lake Union', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Uncle Eddie''s', 'Pub/brunch', 'South Park', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Patini''s Grille', 'American', 'Stanwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Shrimp Shack', 'Road Trip Ets', 'Stanwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Harry''s Beach House', 'Seafood', 'Stanwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Stilly Diner', 'American b''fast/lunch', 'Stanwood', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Moe''s Coffee', 'Coffee', 'Sultan', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ellie’s at the Airport', 'Diner', 'Tulaip', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Taj Grill and Spice', 'Indian', 'Tulalip', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'La Hacienda', 'Mexican', 'West Seattle', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Playa Bonita', 'Mexican', 'Westwood Village', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Pho Dat', 'Pho', 'Woodinville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Irene''s Thai', 'Thai', 'Woodinville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Chan''s Place', 'Chinese', 'Woodinville', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Walla Walla Steak Co.', 'American', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Journeys East', 'Asian', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Terra Cotta Red', 'Asian Fusin', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Oasis Brazilian Steakhouse', 'Brazilian', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Quil Ceda Casino - The Kitchen', 'Buffet', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Nutty''s Junk Yard Grill', 'Burgers', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Vick''s Burger Shack', 'Burgers', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Best of Chengdu', 'Chinese Szechuan', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Swanky Scoop', 'I''ve Cream', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kanishka Cuisine', 'Indian', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jimmie''s', 'Italian', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Anthony''s Wood Fire Grill', 'Seafood', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Shima Sushi', 'Sushi', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Grillbird', 'Teriyaki', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Toshi''s Teriyaki', 'Teriyaki', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Thai Thai', 'Thai', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Jasmine', 'Thai', NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sushi Zen', 'Sushi', 'Everett, Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kiyama', 'Sushi', 'Lake Stevens', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Kazuko', 'Sushi', 'Edmonds', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Ho Bistro', 'Sushi', 'Everett', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Sushi Spott', 'Sushi', 'Mill Creek', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'T55 Pâtisserie', 'Singapore/French', 'Bothell', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Bow Edison', 'Bakery', 'Mount Vernon', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Il Terrazzo', NULL, NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Cafe Companya', NULL, NULL, m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Lord Fletcher''s', 'Prime Rib', 'Palm Springs', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

INSERT INTO restaurants (family_id, name, cuisine, address, created_by)
  SELECT f.id, 'Take 5 Cafe', 'American', 'Ballard', m.id
  FROM families f JOIN members m ON m.family_id = f.id
  WHERE f.invite_code = 'Tiny2019' AND m.name = 'Brian Dickinson';

-- Insert 103 reviews

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny - upscale - need reservation'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Bistro San Martin' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Reservation recommended - other locations'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'El Gaucho' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'mentaiko udon, served with uni'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Tendon Kohaku' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Ashland Brewery' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Boundary Bay Brewing' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Naan and Brew' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Dianna''s Italian' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Jalapeno''s' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Formerly Blotto in Cap Hill'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Starla''s' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Pel'' meni' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Bushara''s Thai' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Black Sheep' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, 'Cost: $; Very casual, almost fast food like - dine in available'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Ta Joia - Latin Korean fusion' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Cost: $$; Casual, dine in - best flan. Burrito a bit dry (but can add wet).'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Julio’s - Mexican' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Railroad Pub & Pizza' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Bento box is heavy on tempura. Try rolls and nigiri in future.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Sakura (sushi)' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$$$'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Bateau' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Highly rated in Seattle Times'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Blotto' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Award winning - My Hot Date specialty pie'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Niles Peacock Pizza' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Lobster roll'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Market' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny - Mon-Sat - 11:30 - 8:30, Sun Brunch 10:00 - 2:00. Oysters on Mondays'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Buck''s American Cafe' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Monday – Friday 7 AM to 2 PM | Saturday & Sunday 7 AM to 3 PM.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Totem Family diner' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Closed Tuesday.  2616 Colby'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Frying Lemon Fish' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Take out only'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Curries' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, '631 N Broadway - great Reuben'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = '7th Street Pub' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, '2803 Colby'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Botan Ramen n Bar' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny - Waterfront'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Wood Fire Grill' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Cost: $$; Prawns are fab. Beer battered fries default. Fresh cut on request (order extra crisp)'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Scuttlebutt' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$$$; Steve from Bistro San Martin'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = '16Eleven' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, 'Very good and broad menu. Happy hour deals until 7:00. Lunch specials too.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Katana' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Visit Theo''s chocolate store'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Local Tide' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, 'Best pizza so far'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Omega Pizza' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Former tea house'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'North Star Diner' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Detroit/Chicago style'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Windy City Pie' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, NULL
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Purple Dot' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Pak Mor, Thai Pink Aoup and Pad See Ew'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'E-Jae Pak Mor' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 10, 'Chase & Rob recommended'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Lucky House' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Great food'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Bella Balducci''s - Persian Fod' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Enjoyed soups and entree''s. Egg rolls disappointing.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Lucky Dragon' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Cost: $$; Has GF pizza'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Conto''s' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Good bar for Kraken games - food not so good'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Razzle' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Chain - Marysville ia newest location. Monday and Saturday night specials'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Buzz Inn' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Same owners as Buzz Inn'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'LJ Bistro' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, NULL
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Hawkeye''s Pub' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Steve from Bistro San Martin'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'T&T Seafood' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Seattle Times recommendation'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Kabob Korner' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Mall sushi - mediocre'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Biddy Fish' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 10, NULL
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Isarn soul kitchen' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Mama hot pot secret menu'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'TK Noodle' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Good Moo Shu Pork. Egg foo yung was not good'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Beijing Chinese Cuisine' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 4, 'Cost: $; Diner'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Don’s 24 hour cafe' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Next to Holiday Inn'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Korea House' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Next to Alvie''s'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Pho' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Pickleball'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Volli' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Woodinville and Edmonds'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Rusty Pelican' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Breakfast and Lunch - same owners as Mukilteo Speedway Cafe'''
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Sawmill Cafe' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Steve from Bistro San Martin'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Clay Pit' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$$$; Steve from Bistro San Martin'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Rare Society' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Smokey roll'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Momo Sushi' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Great pork chops'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Lewis and Main' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, 'Cost: $$; Great food - italian and greek. Casual. Reasonable.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Bella Balducci''s - Med Food' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny - Open Daily: 7:30 a.m. – 3:30 p.m.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Calico Cupboard' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Chicken parm'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'I''ll Granaio' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'COA' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Khachapuri'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Skalka' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Since the 1960''s'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Pancake Chef' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Dungeoness crab Benedict'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Portage Bay' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Great patio. https://www.youtube.com/watch?v=Gbl3uIWwGRg'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Don Lucho''s' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'https://www.seattletimes.com/life/food-drink/restaurant-review-this-seattle-food-hall-has-the-look-feel-and-flavors-of-a-southeast-asian-market/'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Asean Streat Food Hall' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$$$; BEST sushi make reservation, arrive 1 hour early to sit at the bar and chat with Shiro'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Kashiba' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, '655 South King Street, Seattle, WA 98104'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Tai Tung' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Sister was Cafe'' Presse'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'LePichet' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Stone ground South American hot chocolate'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Rey Amago Chocolate Shop' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Small plates, grilled octopus is a must'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Ciudad - bar and grill' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, '(Prime Rib) nice ambience. Sandwiches are just ok'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Cabbage Patch' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$ - $$$; Great food - Reservation Closed Mon & Tue; Wed & Thur 3-10; Fri & Sat 3-11;Sun 3-9'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'The Repp' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Snohomish Bakery' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Recommended for Burgers'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Oxford Saloon' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 4, 'Cost: $'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Hops and Drops' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Recommended for Breakfast'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Jake''s Cafe''' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Steak and rack of lamb. Said to be very good'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Roger’s Riverside Bistro' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Cost: $$'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'El Paraiso Mexican Grill' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Did not enjoy'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Westside Pizza' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 6, 'Cost: $$; Very good food - don’t order the pasta'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Andy’s Fish House' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Wood fired pizza and other items'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Trail''s End' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, '4-9 Tues - Sat. Recommended by an island local.'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Patini''s Grille' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Closed Monday and Tuesday'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Stilly Diner' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Moe''s Coffee' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 4, 'Cost: $; At airport - best for breakfast'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Ellie’s at the Airport' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 8, 'Cost: $$; Very good flavors'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Taj Grill and Spice' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 4, 'Cost: $$; Decent food, bad flan'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'La Hacienda' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $; Granite Falls & Marysville'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Playa Bonita' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Cost: $$$$; Brunch Sat & Sun, reservations 9:00-1:00'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Walla Walla Steak Co.' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'At the casino. Recommended for Sushi'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Journeys East' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny Friday: 11am - 10pm, Saturday: 4pm - 10pm, Sunday: 4pm - 9pm'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Terra Cotta Red' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Notes'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Oasis Brazilian Steakhouse' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Ginny - upscale - need reservation'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Nutty''s Junk Yard Grill' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Try vanilla'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Swanky Scoop' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Steve from Bistro San Martin'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Shima Sushi' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Hawaii fusion'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Grillbird' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'The original inventor'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Toshi''s Teriyaki' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Anthony Borden'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Lord Fletcher''s' AND r.family_id = f.id
  LIMIT 1;

INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)
  SELECT r.id, m.id, 7, 'Meatloaf Sammie'
  FROM restaurants r
  JOIN members m ON m.name = 'Brian Dickinson'
  JOIN families f ON f.id = m.family_id AND f.invite_code = 'Tiny2019'
  WHERE r.name = 'Take 5 Cafe' AND r.family_id = f.id
  LIMIT 1;
