#!/usr/bin/env python3
"""Parse Brian's restaurant spreadsheet and generate seed SQL for D1."""

import sys
import os
import re

try:
    import openpyxl
except ImportError:
    print("Error: openpyxl not installed. Run: pip3 install openpyxl")
    sys.exit(1)

INVITE_CODE = "Tiny2019"
MEMBER_NAME = "Brian Dickinson"
MEMBER_EMAIL = "bsdickinson@gmail.com"

# Star string → 1-10 score
STAR_MAP = {
    "*": 2,
    "**": 4,
    "***": 6,
    "****": 8,
    "*****": 10,
}

# Default score for entries with notes but no valid star rating
DEFAULT_SCORE = 7


def parse_stars(raw):
    """Convert star string to 1-10 score, or None if not a valid star rating."""
    if raw is None:
        return None
    cleaned = str(raw).strip()
    if not cleaned:
        return None
    # Only count if it's purely asterisks (with optional whitespace)
    stars_only = cleaned.replace(" ", "")
    if stars_only in STAR_MAP:
        return STAR_MAP[stars_only]
    return None


def escape_sql(value):
    """Escape a string for SQL single-quote literals."""
    if value is None:
        return None
    return str(value).replace("'", "''")


def build_notes(cost, notes):
    """Combine cost and notes into a single notes string."""
    parts = []
    if cost:
        cost_str = str(cost).strip()
        if cost_str:
            parts.append(f"Cost: {cost_str}")
    if notes:
        notes_str = str(notes).strip()
        if notes_str:
            parts.append(notes_str)
    return "; ".join(parts) if parts else None


def parse_spreadsheet(filepath):
    """Parse xlsx and return deduplicated restaurant entries."""
    wb = openpyxl.load_workbook(filepath, read_only=True)
    ws = wb.active

    entries = []
    seen = set()
    skipped_no_name = 0
    skipped_duplicate = 0

    for i, row in enumerate(ws.iter_rows(values_only=True)):
        # Skip header row
        if i == 0:
            continue

        name = row[0]
        if name is None or not str(name).strip():
            skipped_no_name += 1
            continue

        name = str(name).strip()
        cuisine = str(row[2]).strip() if row[2] else None
        city = str(row[3]).strip() if row[3] else None
        rating_raw = row[4]
        cost = row[6]
        notes_raw = row[7]

        # Dedup by lowercase(name + city)
        dedup_key = (name.lower(), (city or "").lower())
        if dedup_key in seen:
            skipped_duplicate += 1
            continue
        seen.add(dedup_key)

        score = parse_stars(rating_raw)
        notes = build_notes(cost, notes_raw)

        # If there are notes but no star score, assign default
        has_review = score is not None or notes is not None
        if has_review and score is None:
            score = DEFAULT_SCORE

        entries.append({
            "name": name,
            "cuisine": cuisine,
            "city": city,
            "score": score,
            "notes": notes,
            "has_review": has_review,
        })

    wb.close()

    print(f"Parsed: {len(entries)} unique restaurants")
    print(f"Skipped: {skipped_no_name} no-name, {skipped_duplicate} duplicates")
    print(f"With reviews: {sum(1 for e in entries if e['has_review'])}")

    return entries


def generate_sql(entries):
    """Generate SQL statements for seeding the database."""
    lines = []
    lines.append("-- Auto-generated by seed-brian-restaurants.py")
    lines.append("-- DO NOT EDIT MANUALLY")
    lines.append("")

    # Create Brian as member
    lines.append("-- Create Brian as a member of The Butlers family")
    lines.append(f"INSERT OR IGNORE INTO members (family_id, name, is_admin, email)")
    lines.append(f"  SELECT id, '{escape_sql(MEMBER_NAME)}', 0, '{escape_sql(MEMBER_EMAIL)}'")
    lines.append(f"  FROM families WHERE invite_code = '{escape_sql(INVITE_CODE)}';")
    lines.append("")

    # Insert restaurants
    lines.append(f"-- Insert {len(entries)} restaurants")
    lines.append("")

    for entry in entries:
        name_esc = escape_sql(entry["name"])
        cuisine_val = f"'{escape_sql(entry['cuisine'])}'" if entry["cuisine"] else "NULL"
        city_val = f"'{escape_sql(entry['city'])}'" if entry["city"] else "NULL"

        lines.append(f"INSERT INTO restaurants (family_id, name, cuisine, address, created_by)")
        lines.append(f"  SELECT f.id, '{name_esc}', {cuisine_val}, {city_val}, m.id")
        lines.append(f"  FROM families f JOIN members m ON m.family_id = f.id")
        lines.append(f"  WHERE f.invite_code = '{escape_sql(INVITE_CODE)}' AND m.name = '{escape_sql(MEMBER_NAME)}';")
        lines.append("")

    # Insert reviews (only where we have a score or notes)
    review_entries = [e for e in entries if e["has_review"]]
    lines.append(f"-- Insert {len(review_entries)} reviews")
    lines.append("")

    for entry in review_entries:
        name_esc = escape_sql(entry["name"])
        score = entry["score"]
        notes_val = f"'{escape_sql(entry['notes'])}'" if entry["notes"] else "NULL"

        lines.append(f"INSERT OR IGNORE INTO reviews (restaurant_id, member_id, overall_score, notes)")
        lines.append(f"  SELECT r.id, m.id, {score}, {notes_val}")
        lines.append(f"  FROM restaurants r")
        lines.append(f"  JOIN members m ON m.name = '{escape_sql(MEMBER_NAME)}'")
        lines.append(f"  JOIN families f ON f.id = m.family_id AND f.invite_code = '{escape_sql(INVITE_CODE)}'")
        lines.append(f"  WHERE r.name = '{name_esc}' AND r.family_id = f.id")
        lines.append(f"  LIMIT 1;")
        lines.append("")

    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <path-to-xlsx>")
        sys.exit(1)

    xlsx_path = sys.argv[1]
    if not os.path.exists(xlsx_path):
        print(f"Error: File not found: {xlsx_path}")
        sys.exit(1)

    entries = parse_spreadsheet(xlsx_path)
    sql = generate_sql(entries)

    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed-brian-restaurants.sql")
    with open(output_path, "w") as f:
        f.write(sql)

    print(f"Generated: {output_path}")


if __name__ == "__main__":
    main()
